name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run : |
          pip install uv
          uv pip install --system -r requirements.txt
      - run: |
          jupyter execute notebooks/example.ipynb
