name: notebooks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pypi:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-13", "windows-latest"]
        python-version: ["3.8", "3.9"]
    runs-on: ${{ matrix.os }}
    name: "${{ matrix.os }} :: pypi :: ${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - if: matrix.os == 'macos-13'
        run: brew install libomp
      - name: Install dependencies from PyPI
        run : |
          pip install uv
          uv pip install --system -r requirements.txt
      - name: Execute example notebooks
        run: |
          jupyter execute notebooks/example.ipynb
      - name: Execute example scripts from ZhaoWenzhao/QHCC
        run: |
          git clone https://github.com/ZhaoWenzhao/QHCC.git
          cd QHCC
          python demo_QHCC_XGBoost.py
  conda-forge:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-13"]
    runs-on: ${{ matrix.os }}
    name: "${{ matrix.os }} :: conda-forge"
    timeout-minutes: 15
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          condarc: |
            channels:
              - conda-forge
              - radiomics
      - name: Execute example notebooks
        run: |
          jupyter execute notebooks/example.ipynb
      - name: Execute example scripts from ZhaoWenzhao/QHCC
        run: |
          git clone https://github.com/ZhaoWenzhao/QHCC.git
          cd QHCC
          python demo_QHCC_XGBoost.py
